server:
  port: 8090
  compression:
    enabled: true

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders-group-id

app:
  sending:
    topic:
      name: default
  receiving:
    topic:
      name: self

logging:
  pattern:
    console: "%-5level: %class{0} - %msg%n"
  level:
    root: INFO
    org.springframework: DEBUG
    com.example.zhangirakzhan: INFO