DROP ALL OBJECTS;

CREATE SCHEMA IF NOT EXISTS PUBLIC;

SET SCHEMA PUBLIC;

CREATE TABLE USERS (
    ID BIGINT PRIMARY KEY,
    ROLE VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCTS (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PRICE DOUBLE NOT NULL
);



CREATE TABLE ADDRESSES (
    ID BIGINT PRIMARY KEY,
    COUNTRY VARCHAR(255) NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    POSTAL_CODE VARCHAR(255) NOT NULL,
    USER_ID BIGINT,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE ORDERS (
    ID BIGINT PRIMARY KEY,
    QUANTITY DOUBLE NOT NULL,
    USER_ID BIGINT,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);



CREATE TABLE ORDER_PRODUCT (
    ORDER_ID BIGINT,
    PRODUCT_ID BIGINT,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID)
);
